global using SurveyBasket.Models;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SurveyBasket.Contracts.Auth;
global using SurveyBasket.Contracts.Polls;
global using SurveyBasket.Services;
global using FluentValidation;
global using Mapster;
global using FluentValidation.AspNetCore;